ALTER TABLE tours_pen ADD COLUMN destino VARCHAR(100) NULL, ADD COLUMN categoria VARCHAR(100) NULL;
ALTER TABLE tours_usd ADD COLUMN destino VARCHAR(100) NULL, ADD COLUMN categoria VARCHAR(100) NULL;
